feat: pagination: adds pagination component
EightfoldAI/octuple pull request #121
Opened 2022-05-17 01:29 UTC by dkilgore-eightfold

2022-05-17 06:01 UTC, ychhabra-eightfold requested changes

2022-05-17 06:01 UTC, ychhabra-eightfold commented on src/components/Pagination/Pagination.tsx
> +                onCurrentChange && onCurrentChange(_currentPage);
same as above

2022-05-17 06:01 UTC, ychhabra-eightfold commented on src/components/Pagination/Pagination.tsx
> +                onCurrentChange && onCurrentChange(val);
same as above

2022-05-17 06:02 UTC, ychhabra-eightfold commented
How to use the goto input doesnt seem to work for me, also the page selector doesnt seem to work sometimes

2022-05-17 16:04 UTC, dkilgore-eightfold commented on src/components/Pagination/Pagination.tsx
> +                            <DefaultButton
We can use props for these, will add.

2022-05-17 16:07 UTC, dkilgore-eightfold commented
> How to use the goto input doesnt seem to work for me, also the page selector doesnt seem to work sometimes

For the Goto button to work you'll need the latest main - as there was a bug where onChange was doing nothing in Input. Regarding the page selector, this may be some other issue. Works for me on a few browsers, so may be some other issue related to Menu component

2022-05-17 19:00 UTC, dkilgore-eightfold commented on src/components/Pagination/Pagination.tsx
> +                            <DefaultButton
That being said, there's no real need for aria-labels for buttons that only contain a count. Will add aria-label support for the icon buttons only.

2022-05-17 19:01 UTC, dkilgore-eightfold commented on src/components/Pagination/Pager.tsx
> +                }
Not as readable, but will apply.

2022-05-17 19:01 UTC, dkilgore-eightfold commented on src/components/Pagination/Pager.tsx
> +            const pagerCount: number = 7;
Added comment, keeping scoped.

2022-05-17 19:02 UTC, dkilgore-eightfold commented on src/components/Pagination/Pager.tsx
> +            if (currentPage > 5 && !(currentPage < pageCount - 5)) {
Moved these to a constant

2022-05-17 19:28 UTC, dkilgore-eightfold commented on src/components/Pagination/Pager.tsx
> +                }
Keeping the legible loop for now.

2022-05-18 05:35 UTC, ychhabra-eightfold approved these changes

2022-05-18 05:35 UTC, ychhabra-eightfold commented
LGTM, updaten snapshots before merging

2022-05-18 16:41 UTC, merged