feat: add Accordion component
EightfoldAI/octuple pull request #126
Opened 2022-05-20 09:05 UTC by ayadav-eightfold

## SUMMARY:

## GITHUB ISSUE (Open Source Contributors)

## JIRA TASK (Eightfold Employees Only):

## CHANGE TYPE:

-   [ ] Bugfix Pull Request
-   [ ] Feature Pull Request

## TEST COVERAGE:

-   [ ] Tests for this change already exist
-   [ ] I have added unittests for this change

## TEST PLAN:

2022-05-20 09:09 UTC, pbahukhandi-eightfold commented on src/components/Accordion/accordion.module.scss
> +    border: 1px solid #d9dce1;
Colors should be according to themes ?

2022-05-20 09:10 UTC, ayadav-eightfold commented on src/components/Accordion/Accordion.stories.tsx
> +                <p>With loadddddssso f content</p>
Update stories text
Use button in Summary component

2022-05-20 09:15 UTC, ayadav-eightfold commented on src/components/Accordion/Accordion.tsx
> +        <button className={styles.accordionSummaryStyle} onClick={onClick}>
Use aria-label and role button for accessibility

2022-05-20 09:28 UTC, ychhabra-eightfold requested changes

2022-05-20 09:28 UTC, ychhabra-eightfold commented on src/components/Accordion/accordion.module.scss
> +.accordionContainerStyle {
class names should be in snake case

2022-05-20 09:28 UTC, ychhabra-eightfold commented on src/components/Accordion/accordion.module.scss
> +    border: 1px solid #d9dce1;
+1 
```suggestion
    border: 1px solid var(--grey-color-20);
```

2022-05-20 09:28 UTC, ychhabra-eightfold commented on src/components/Accordion/Accordion.types.ts
> +    children: React.ReactNode;
this can be removed as FC already handdles this

2022-05-20 09:28 UTC, ychhabra-eightfold commented on src/components/Accordion/Accordion.types.ts
> +    summary: HTMLElement | string;
```suggestion
    summary: React.ReactNode | string;
```

2022-05-20 09:28 UTC, ychhabra-eightfold commented on src/components/Accordion/Accordion.tsx
> +    expandIconProps = { path: IconName['mdiChevronDown'] },
```suggestion
    expandIconProps = { path: IconName.mdiChevronDown },
```

2022-05-20 09:28 UTC, ychhabra-eightfold commented on src/components/Accordion/Accordion.tsx
> +        onAccordionStateChange(expand);
```suggestion
        onAccordionStateChange?.(expand);
```

2022-05-20 09:28 UTC, ychhabra-eightfold commented on src/components/Accordion/Accordion.tsx
> +    const [isAccordionExpanded, setIsAccordionExpanded] =
nit: 
```suggestion
    const [isExpanded, setIsExpanded] =
```

2022-05-20 09:28 UTC, ychhabra-eightfold commented on src/components/Accordion/Accordion.tsx
> +        <div className={accordionContainerStyle}>
handle aria properties, aria-expanded, aria-controls etc

2022-05-20 09:28 UTC, ychhabra-eightfold commented on src/components/Accordion/Accordion.tsx
> +        <button className={styles.accordionSummaryStyle} onClick={onClick}>
Use Octuple buttons here

2022-05-20 09:28 UTC, ychhabra-eightfold commented on src/components/Accordion/Accordion.types.ts
> +    extends Omit<AccordionProps, 'onAccordionStateChange' | 'summary'> {
I would rather create AccordionBaseProps if you have to omit it in two places ?

2022-05-20 09:28 UTC, ychhabra-eightfold commented on src/components/Accordion/accordion.module.scss
> +        transition: all $motion-duration-fast $motion-easing-easeout;
can we also translate the accordian opening rather than just the body

2022-05-20 17:10 UTC, ayadav-eightfold commented
explore fliptoolkit for animation

2022-05-20 17:12 UTC, ayadav-eightfold commented
refer to split and toggle button for aria attributes

2022-05-20 17:15 UTC, ayadav-eightfold commented
Wrap multiple accordions in list component for better accessibility

2022-05-20 17:45 UTC, ayadav-eightfold commented on src/components/Accordion/Accordion.tsx
> +            onClick={onClick}
Use div with button role and aria attributes.

2022-05-20 17:47 UTC, ayadav-eightfold commented on src/components/Accordion/Accordion.stories.tsx
> +                <div>
Add example with Icon & Badge

2022-05-23 23:37 UTC, dkilgore-eightfold approved these changes

2022-05-24 08:00 UTC, ychhabra-eightfold commented on src/components/Accordion/Accordion.tsx
> +            id,
```suggestion
            id = /// Generate a unqiue id,
```

2022-05-24 08:02 UTC, ychhabra-eightfold commented on src/components/Accordion/Accordion.tsx
> +            }
```suggestion
             event.key === 'Enter'  &&   onClick?.(event);
           
```

2022-05-24 14:59 UTC, ychhabra-eightfold approved these changes

2022-05-24 15:51 UTC, merged