feat: added support for icomoon icons
EightfoldAI/octuple pull request #127
Opened 2022-05-20 16:36 UTC by ayadav-eightfold

Added support for icomoon

2022-05-20 17:06 UTC, ayadav-eightfold commented on src/components/Icomoon/Icon.tsx
> +                    <IcomoonReact
Add aria and role attributes

2022-05-20 17:07 UTC, ayadav-eightfold commented on src/components/Icomoon/Icon.types.ts
> +     */
update props

2022-05-20 17:11 UTC, ychhabra-eightfold requested changes

2022-05-20 17:11 UTC, ychhabra-eightfold commented on src/components/Icomoon/Icon.stories.tsx
> +    <IcomoonProvider value={iconSet}>
Let move this to the config provider

2022-05-20 17:11 UTC, ychhabra-eightfold commented on src/components/Icomoon/Icon.tsx
> +            <IconSetContext.Consumer>
Can we move this to this icon component based on a prop return material icon or icomooon icon ? So one component can serve both purposes.

2022-05-20 17:11 UTC, ychhabra-eightfold commented on src/components/Icomoon/selection.json
> +    "IcoMoonType": "selection",
i hope this is a sample just for the storybook

2022-05-20 17:11 UTC, ychhabra-eightfold commented on package.json
> +        "icomoon-react": "^3.0.0",
```suggestion
        "icomoon-react": "3.0.0",
```

2022-05-20 17:55 UTC, ayadav-eightfold commented on src/components/Icomoon/Icon.tsx
> +const IconSetContext = React.createContext<object | null>(null);
Merge with Icon Component

2022-05-23 05:50 UTC, ychhabra-eightfold commented
Closing pr as this duplicates https://github.com/EightfoldAI/octuple/pull/129

2022-05-23 05:50 UTC, closed without merging