chore: added enhancements to dropdown to support icon and improved accessibilty
EightfoldAI/octuple pull request #130
Opened 2022-05-22 18:22 UTC by ayadav-eightfold

added enhancements to dropdown to support icon and improved accessibilty

2022-05-23 05:04 UTC, ychhabra-eightfold requested changes
Let make the changes as discussed on call

2022-05-23 23:39 UTC, dkilgore-eightfold approved these changes

2022-05-24 07:54 UTC, ychhabra-eightfold commented on src/components/Dropdown/Dropdown.tsx
> +            {...containerProps}
```suggestion
            {...TRIGGER_TO_HANDLER_MAP_ON_LEAVE[trigger] ? {TRIGGER_TO_HANDLER_MAP_ON_LEAVE[trigger]: toggle(false) : {}}}
```

2022-05-24 07:55 UTC, ychhabra-eightfold commented on src/components/Dropdown/Dropdown.tsx
> +            refs.reference.current?.contains(e.target)
```suggestion
            refs.reference.current?.contains?.(e.target)
```

2022-05-24 13:17 UTC, ychhabra-eightfold commented on src/hooks/useEventListener.ts
> +        const element = target && getElement(target);
is this needed ?

2022-05-24 14:53 UTC, merged