feat: stack
EightfoldAI/octuple pull request #132
Opened 2022-05-23 15:11 UTC by thiyagaraj-eightfold

## SUMMARY:
Adding a stack component

## GITHUB ISSUE (Open Source Contributors)

## JIRA TASK (Eightfold Employees Only):
https://eightfoldai.atlassian.net/jira/software/c/projects/ENG/boards/20?modal=detail&selectedIssue=ENG-2788&sprint=18&search=stack

## CHANGE TYPE:

-   [ ] Bugfix Pull Request
-   [x] Feature Pull Request

## TEST COVERAGE:

-   [ ] Tests for this change already exist
-   [x] I have added unittests for this change

## TEST PLAN:

2022-05-23 15:18 UTC, thiyagaraj-eightfold commented on src/components/Stack/Stack.tsx
> +        };
Abstract as a function

2022-05-23 23:35 UTC, dkilgore-eightfold requested changes

2022-05-23 23:35 UTC, dkilgore-eightfold commented on src/components/Stack/Stack.types.ts
> +    | 'xxxs'
Is there a way to ensure this snaps to a 16px grid?

2022-05-24 15:39 UTC, dkilgore-eightfold approved these changes

2022-05-24 16:40 UTC, merged