feat: popup: adds popup component
EightfoldAI/octuple pull request #543
Opened 2023-02-21 18:38 UTC by dkilgore-eightfold

## SUMMARY:
Adds `Popup` component, derived from `Tooltip`
Updates `Tooltip` component to enable `Popup` `type` using existing patterns via `floating-ui` dependency
Preserves `Tooltip` existing implementation to minimize risk via `getDefault` and `getPopup` functions
Adds `Popup` story
Adds and updates unit tests

https://user-images.githubusercontent.com/99700808/220430583-b6bd8acd-2961-4015-a770-c08a3e102d10.mp4

## JIRA TASK (Eightfold Employees Only):
ENG-2819

## CHANGE TYPE:

- [ ] Bugfix Pull Request
- [X] Feature Pull Request

## TEST COVERAGE:

- [ ] Tests for this change already exist
- [X] I have added unittests for this change

## TEST PLAN:
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the Tooltip and Popup stories behave as expected.

2023-02-21 18:43 UTC, ypike-eightfold approved these changes

2023-02-22 05:16 UTC, ychhabra-eightfold requested changes

2023-02-22 05:16 UTC, ychhabra-eightfold commented on src/components/Popup/Popup.tsx
> +import React, { FC } from 'react';
add it to octuple.ts

2023-02-23 06:15 UTC, ychhabra-eightfold approved these changes

2023-02-23 16:40 UTC, merged