Adding new icons to be used in calibration page
EightfoldAI/octuple pull request #585
Opened 2023-04-06 23:49 UTC by yhoole-eightfold

## SUMMARY:
Adding new icons to be used in calibration page:
* mdiTrendingDown
* mdiTrendingNeutral 
* mdiTrendingUp

## GITHUB ISSUE (Open Source Contributors)

## JIRA TASK (Eightfold Employees Only):
[ENG-48906](https://eightfoldai.atlassian.net/browse/ENG-48906)

## CHANGE TYPE:

- [ ] Bugfix Pull Request
- [X] Feature Pull Request

## TEST COVERAGE:

- [ ] Tests for this change already exist
- [ ] I have added unittests for this change

## TEST PLAN:

2023-04-06 23:55 UTC, sanjeet-eightfold approved these changes
Looks good. Can you include the screenshot of what they look like before merging?

2023-04-07 00:14 UTC, dkilgore-eightfold requested changes

2023-04-07 00:14 UTC, dkilgore-eightfold commented on src/components/Icon/mdi.ts
> +  mdiTrendingDown = "M16,18L18.29,15.71L13.41,10.83L9.41,14.83L2,7.41L3.41,6L9.41,12L13.41,8L19.71,14.29L22,12V18H16Z",
Single quotes please

2023-04-07 00:18 UTC, dkilgore-eightfold approved these changes

2023-04-07 00:18 UTC, yhoole-eightfold commented on src/components/Icon/mdi.ts
> +  mdiTrendingDown = "M16,18L18.29,15.71L13.41,10.83L9.41,14.83L2,7.41L3.41,6L9.41,12L13.41,8L19.71,14.29L22,12V18H16Z",
done, thank you

2023-04-07 00:28 UTC, merged