feat: messagebar: add message bar component
EightfoldAI/octuple pull request #622
Opened 2023-05-18 22:18 UTC by dkilgore-eightfold

## SUMMARY:
Adds `MessageBar` component to Octuple component library

https://github.com/EightfoldAI/octuple/assets/99700808/cf83e2bb-7e78-468b-8bf3-5971fc0dcaaa

Spec: https://www.figma.com/file/SlKRC7oKF7XZyHMv2op4ch/Octuple-DS-(Theme-2)?type=design&node-id=869-1503&t=TWznJ6gD2O0HHNnW-0

## JIRA TASK (Eightfold Employees Only):
ENG-2812

## CHANGE TYPE:

- [ ] Bugfix Pull Request
- [x] Feature Pull Request

## TEST COVERAGE:

- [ ] Tests for this change already exist
- [x] I have added unittests for this change

## TEST PLAN:
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `MessageBar` stories behave as expected.

2023-05-18 22:29 UTC, ypike-eightfold approved these changes
Looks good. I will also test it with stage link to check Gilroy.

2023-05-19 06:59 UTC, ychhabra-eightfold requested changes

2023-05-19 06:59 UTC, ychhabra-eightfold commented on src/components/MessageBar/MessageBar.tsx
> +    };
a map would be nice here

2023-05-24 15:51 UTC, ychhabra-eightfold approved these changes

2023-05-24 16:49 UTC, merged