feat: adds modal component
EightfoldAI/octuple pull request #65
Opened 2022-04-18 04:59 UTC by yrchhabra-eightfold

2022-04-18 15:30 UTC, dylankilgore requested changes

2022-04-18 15:30 UTC, dylankilgore commented on src/components/Modal/Modal.tsx
> +        { [styles.large]: size === ModalSize.large },
Need Fullscreen modal too, there are many scenarios and existing features in the product that require this.

2022-04-18 15:30 UTC, dylankilgore commented on src/components/Modal/Modal.types.ts
> +    large = 'large',
fullscreen

2022-04-18 15:42 UTC, dylankilgore requested changes

2022-04-18 15:42 UTC, dylankilgore commented on src/components/Dialog/BaseDialog/BaseDialog.tsx
> +                <div className={bodyClassName}>{body}</div>
To make this scrollable you may consider adding a bodyMaxHeight prop. then refer to line 57 in the Modal.js common component in vscode `www/react/src/lib/common/Modal.js`. We either take the specified height or calculate it using the viewport, taking into account any variable insets and heights of the header and footer.

2022-04-18 15:42 UTC, dylankilgore commented on src/components/Dialog/BaseDialog/BaseDialog.tsx
> +                <div className={bodyClassName}>{body}</div>
You may also look at line 136 of the Modal common component scss to see the default calc for some ideas --> `www/react/src/styles/Modal.scss`

2022-04-20 15:09 UTC, dkilgore-eightfold approved these changes

2022-04-20 15:22 UTC, merged