chore: usegestures: wrap event listeners with useCallback
EightfoldAI/octuple pull request #752
Opened 2023-11-20 08:17 UTC by schakka-eightfold

## SUMMARY:
Wrap event listeners in useGestures hook with useCallback to not overload the browser whenever an action is performed

## GITHUB ISSUE (Open Source Contributors)
NA

## JIRA TASK (Eightfold Employees Only):
ENG-70944

## CHANGE TYPE:

- [] Bugfix Pull Request
- [X] Feature Pull Request

## TEST COVERAGE:

- [X] Tests for this change already exist
- [ ] I have added unittests for this change

## TEST PLAN:
Pull the PR branch and run `yarn` and `yarn storybook`. Verify the `Popup` and `Tooltip` stories behave as expected.

2023-11-20 08:19 UTC, ychhabra-eightfold requested changes

2023-11-20 08:19 UTC, ychhabra-eightfold commented on src/hooks/useGestures.ts
> +  });
```suggestion
  }, []);
```

2023-11-20 08:19 UTC, ychhabra-eightfold commented on src/hooks/useGestures.ts
> +  });
do this everywhere

2023-11-20 08:20 UTC, schakka-eightfold commented on src/hooks/useGestures.ts
> +  });
Updated

2023-11-27 15:35 UTC, ychhabra-eightfold approved these changes

2023-11-27 16:29 UTC, dkilgore-eightfold requested changes

2023-11-27 16:29 UTC, dkilgore-eightfold commented on src/hooks/useGestures.test.tsx
> +    // expect(result.current).toBe(Gestures.SwipeDown);
use test.skip rather than comment.

2023-11-27 16:29 UTC, dkilgore-eightfold commented on src/components/Tooltip/Tooltip.test.tsx
> +  // test('Tooltip uses touch to show, hide and show again', async () => {
use test.skip rather than comment.

2023-11-27 16:33 UTC, dkilgore-eightfold commented on src/hooks/useGestures.ts
> +  const onMouseMove = useCallback(
Rather than a useCallback, let's use a debounce.

2023-11-27 16:35 UTC, schakka-eightfold commented on src/hooks/useGestures.test.tsx
> +    // expect(result.current).toBe(Gestures.SwipeDown);
Updated

2023-11-27 16:36 UTC, schakka-eightfold commented on src/components/Tooltip/Tooltip.test.tsx
> +  // test('Tooltip uses touch to show, hide and show again', async () => {
Updated

2023-11-27 17:40 UTC, dkilgore-eightfold commented on src/hooks/useGestures.ts
>    const [touchStartY, setTouchStartY] = useState<number>(0);
update startTime, touchStartX, and touchStartY to useRef vars.

2023-11-27 17:43 UTC, dkilgore-eightfold commented on src/hooks/useGestures.ts
>    const attachGestures = (): void => {
These functions may be removed and the listeners placed directly in a useMemo instead of useEffect.

2023-11-27 18:30 UTC, dkilgore-eightfold approved these changes

2023-11-27 18:31 UTC, merged