Slider component rough first pass. Additional commit for dev cleanliness.
EightfoldAI/octuple pull request #88
Opened 2022-05-01 15:45 UTC by phrough

2022-05-02 15:48 UTC, dkilgore-eightfold commented
@phrough please refer to the Octuple [contribution guidelines](https://github.com/EightfoldAI/octuple/blob/main/src/CONTRIBUTING.md)

2022-05-02 16:27 UTC, dkilgore-eightfold commented on src/components/Slider/slider.module.scss
> +.sliderContainer {
nit: consistency in class names, snake case vs camel. Snake is recommended.

2022-05-02 16:32 UTC, dkilgore-eightfold requested changes

2022-05-02 16:32 UTC, dkilgore-eightfold commented on src/components/Slider/Slider.tsx
> +export const Slider: FC<SliderProps> = ({ value, min = 0, max = 100 }) => {
Stub in basic UT

2022-05-02 16:33 UTC, dkilgore-eightfold commented on src/components/Slider/slider.module.scss
> +    color: #666;
Take note of other component use of color palette and css vars to enable theming.

2022-05-02 16:35 UTC, dkilgore-eightfold commented on src/CONTRIBUTING.md
> +### `yarn install`
Please read the section on commits, we use commit lint and you'll need to update the title of your pr to something like feat: slider: adds slider component.

2022-05-03 00:36 UTC, phrough commented on src/CONTRIBUTING.md
> +### `yarn install`
Will do. Was unclear on the relationship between commits and the PR. Am separating the two commits out into independent PRs. Probably the preferred way I would guess?

2022-05-03 04:51 UTC, phrough commented
Apologies. I screwed this up for lack of familiarity with the workflow. I'm going to close this PR and submit a new one with feedback addressed.

2022-05-03 04:51 UTC, closed without merging