fix: scroller is interrupting with the mouse events even when it is not visible
EightfoldAI/octuple pull request #920
Opened 2024-12-11 07:45 UTC by spradhan-eightfold

## SUMMARY:
Left scroller button in Table row interrupts with mouse events like hover popup, even when it is not visible.

## GITHUB ISSUE (Open Source Contributors)

## JIRA TASK (Eightfold Employees Only):
https://eightfoldai.atlassian.net/browse/ENG-121104

## CHANGE TYPE:

- [x] Bugfix Pull Request
- [ ] Feature Pull Request

## TEST COVERAGE:

- [x] Tests for this change already exist
- [ ] I have added unittests for this change

## TEST PLAN:
1. pull branch down locally and build and sync with vscode octuple module under node modules.
2. Verify the hover on Demand pipeline page of resourcing.

2024-12-11 15:31 UTC, ychhabra-eightfold requested changes

2024-12-11 15:31 UTC, ychhabra-eightfold commented on src/components/Table/Internal/Body/Scroller.tsx
> +            visibility: startButtonVisible && visible ? 'visible' : 'hidden',
endButtonVisible

2024-12-11 15:45 UTC, spradhan-eightfold commented on src/components/Table/Internal/Body/Scroller.tsx
> +            visibility: startButtonVisible && visible ? 'visible' : 'hidden',
Corrected.

2024-12-12 09:21 UTC, ychhabra-eightfold approved these changes

2024-12-12 09:38 UTC, merged